platform :ios, '8.1'
inhibit_all_warnings!
use_frameworks!

target 'GFCoreDataSource_Example' do
  pod 'GFCoreDataSource', :path => '../'
  pod 'Masonry'

  target 'GFCoreDataSource_Tests' do
    inherit! :search_paths

    
  end
end
